name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'feed.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        node-version: '20'

    - name: Set up Jekyll
      uses: helaili/jekyll-action@2.0.4
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}

    - name: Build and deploy
      run: |
        bundle install
        bundle exec jekyll build
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Rebuild site'
        git push
